# Generated by Django 3.0.6 on 2020-07-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=10, null=True)),
                ('size', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
